// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: HelloServer.proto
// </auto-generated>
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcServer {
  /// <summary>
  /// The greeting service definition.
  /// </summary>
  public static partial class HelloServer
  {
    static readonly string __ServiceName = "GrpcServer.HelloServer";

    static readonly grpc::Marshaller<global::GrpcServer.HelloRequest> __Marshaller_GrpcServer_HelloRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcServer.HelloRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcServer.HelloReply> __Marshaller_GrpcServer_HelloReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcServer.HelloReply.Parser.ParseFrom);

    static readonly grpc::Method<global::GrpcServer.HelloRequest, global::GrpcServer.HelloReply> __Method_SayHello = new grpc::Method<global::GrpcServer.HelloRequest, global::GrpcServer.HelloReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_GrpcServer_HelloRequest,
        __Marshaller_GrpcServer_HelloReply);

    static readonly grpc::Method<global::GrpcServer.HelloRequest, global::GrpcServer.HelloReply> __Method_SayHelloOneStremOne = new grpc::Method<global::GrpcServer.HelloRequest, global::GrpcServer.HelloReply>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SayHelloOneStremOne",
        __Marshaller_GrpcServer_HelloRequest,
        __Marshaller_GrpcServer_HelloReply);

    static readonly grpc::Method<global::GrpcServer.HelloRequest, global::GrpcServer.HelloReply> __Method_SayHelloOneStremTwo = new grpc::Method<global::GrpcServer.HelloRequest, global::GrpcServer.HelloReply>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "SayHelloOneStremTwo",
        __Marshaller_GrpcServer_HelloRequest,
        __Marshaller_GrpcServer_HelloReply);

    static readonly grpc::Method<global::GrpcServer.HelloRequest, global::GrpcServer.HelloReply> __Method_SayHelloTwoStrem = new grpc::Method<global::GrpcServer.HelloRequest, global::GrpcServer.HelloReply>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "SayHelloTwoStrem",
        __Marshaller_GrpcServer_HelloRequest,
        __Marshaller_GrpcServer_HelloReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcServer.HelloServerReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of HelloServer</summary>
    [grpc::BindServiceMethod(typeof(HelloServer), "BindService")]
    public abstract partial class HelloServerBase
    {
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::GrpcServer.HelloReply> SayHello(global::GrpcServer.HelloRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task SayHelloOneStremOne(global::GrpcServer.HelloRequest request, grpc::IServerStreamWriter<global::GrpcServer.HelloReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::GrpcServer.HelloReply> SayHelloOneStremTwoAsync(grpc::IAsyncStreamReader<global::GrpcServer.HelloRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task SayHelloTwoStrem(grpc::IAsyncStreamReader<global::GrpcServer.HelloRequest> requestStream, grpc::IServerStreamWriter<global::GrpcServer.HelloReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for HelloServer</summary>
    public partial class HelloServerClient : grpc::ClientBase<HelloServerClient>
    {
      /// <summary>Creates a new client for HelloServer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public HelloServerClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for HelloServer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public HelloServerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected HelloServerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected HelloServerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::GrpcServer.HelloReply SayHello(global::GrpcServer.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::GrpcServer.HelloReply SayHello(global::GrpcServer.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::GrpcServer.HelloReply> SayHelloAsync(global::GrpcServer.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::GrpcServer.HelloReply> SayHelloAsync(global::GrpcServer.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::GrpcServer.HelloReply> SayHelloOneStremOne(global::GrpcServer.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloOneStremOne(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::GrpcServer.HelloReply> SayHelloOneStremOne(global::GrpcServer.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SayHelloOneStremOne, null, options, request);
      }
      public virtual grpc::AsyncClientStreamingCall<global::GrpcServer.HelloRequest, global::GrpcServer.HelloReply> SayHelloOneStremTwo(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloOneStremTwo(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::GrpcServer.HelloRequest, global::GrpcServer.HelloReply> SayHelloOneStremTwo(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_SayHelloOneStremTwo, null, options);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::GrpcServer.HelloRequest, global::GrpcServer.HelloReply> SayHelloTwoStrem(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloTwoStrem(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::GrpcServer.HelloRequest, global::GrpcServer.HelloReply> SayHelloTwoStrem(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_SayHelloTwoStrem, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override HelloServerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HelloServerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(HelloServerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHello, serviceImpl.SayHello)
          .AddMethod(__Method_SayHelloOneStremOne, serviceImpl.SayHelloOneStremOne)
          .AddMethod(__Method_SayHelloOneStremTwo, serviceImpl.SayHelloOneStremTwoAsync)
          .AddMethod(__Method_SayHelloTwoStrem, serviceImpl.SayHelloTwoStrem).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, HelloServerBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SayHello, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcServer.HelloRequest, global::GrpcServer.HelloReply>(serviceImpl.SayHello));
      serviceBinder.AddMethod(__Method_SayHelloOneStremOne, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::GrpcServer.HelloRequest, global::GrpcServer.HelloReply>(serviceImpl.SayHelloOneStremOne));
      serviceBinder.AddMethod(__Method_SayHelloOneStremTwo, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::GrpcServer.HelloRequest, global::GrpcServer.HelloReply>(serviceImpl.SayHelloOneStremTwoAsync));
      serviceBinder.AddMethod(__Method_SayHelloTwoStrem, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::GrpcServer.HelloRequest, global::GrpcServer.HelloReply>(serviceImpl.SayHelloTwoStrem));
    }

  }
}
#endregion
